name: Deploy to Elastic Beanstalk

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Trigger on merge to main (or your target branch)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24'  # Use the Go version required by your project

      - name: Build Go Binary
        run: |
          go mod tidy
          go build -o main.go

      - name: Zip application
        run: zip -r application.zip .  # Zip the entire repository

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ vars.AWS_BEANSTALK_APP_NAME }}
          environment_name: ${{ vars.AWS_BEANSTALK_ENV_NAME }}
          region: ${{ secrets.AWS_REGION }}
          version_label: "v1.0.2-${{ github.sha }}"
          deployment_package: application.zip  # Deploy the ZIP file